package inbox

import "testing"

func TestMessageIDsExtractsInReplyToThenReferences(t *testing.T) {
	h := hdrOnly(t, `From: bob@example.com
To: alice@example.com
Subject: Re: Hello
In-Reply-To: <a@x>
References: <b@y> <a@x>

Sounds good.
`)
	got := MessageIDs(h)
	want := []string{"<a@x>", "<b@y>", "<a@x>"}
	if !equalStrings(got, want) {
		t.Fatalf("MessageIDs = %v, want %v", got, want)
	}
}

func TestMessageIDsAbsentReturnsEmpty(t *testing.T) {
	h := hdrOnly(t, `From: bob@example.com
To: alice@example.com
Subject: Hello

Hi there.
`)
	got := MessageIDs(h)
	if len(got) != 0 {
		t.Fatalf("MessageIDs = %v, want empty", got)
	}
}

func TestMessageIDsIgnoresTokensWithoutAngleBrackets(t *testing.T) {
	h := hdrOnly(t, `From: bob@example.com
To: alice@example.com
Subject: Re: Hello
References: not-a-message-id <a@x> also-not-one

Hi.
`)
	got := MessageIDs(h)
	want := []string{"<a@x>"}
	if !equalStrings(got, want) {
		t.Fatalf("MessageIDs = %v, want %v", got, want)
	}
}

func TestIsAutoReplyTrueWhenAutoReplied(t *testing.T) {
	h := hdrOnly(t, `From: bot@example.com
To: alice@example.com
Subject: Out of office
Auto-Submitted: auto-replied

I'm out of the office.
`)
	if !IsAutoReply(h) {
		t.Fatal("IsAutoReply = false, want true")
	}
}

func TestIsAutoReplyTrueWhenAutoGenerated(t *testing.T) {
	h := hdrOnly(t, `From: bot@example.com
To: alice@example.com
Subject: Delivery notification
Auto-Submitted: auto-generated

...
`)
	if !IsAutoReply(h) {
		t.Fatal("IsAutoReply = false, want true")
	}
}

func TestIsAutoReplyFalseWhenExplicitlyNo(t *testing.T) {
	h := hdrOnly(t, `From: alice@example.com
To: bob@example.com
Subject: Re: Hello
Auto-Submitted: no

Sounds good.
`)
	if IsAutoReply(h) {
		t.Fatal("IsAutoReply = true, want false")
	}
}

func TestIsAutoReplyFalseWhenAbsent(t *testing.T) {
	h := hdrOnly(t, `From: alice@example.com
To: bob@example.com
Subject: Re: Hello

Sounds good.
`)
	if IsAutoReply(h) {
		t.Fatal("IsAutoReply = true, want false")
	}
}

// Precedence: bulk is a mailing-list signal, not an auto-responder one — it
// must not trip IsAutoReply. Locks in the scoping documented on IsAutoReply.
func TestIsAutoReplyFalseWhenOnlyPrecedenceBulk(t *testing.T) {
	h := hdrOnly(t, `From: list@example.com
To: bob@example.com
Subject: Weekly digest
Precedence: bulk

Digest contents.
`)
	if IsAutoReply(h) {
		t.Fatal("IsAutoReply = true, want false (Precedence: bulk is not scoped)")
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
