apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inroad.fullname" . }}-config
  labels:
    {{- include "inroad.labels" . | nindent 4 }}
data:
  INROAD_ENV: {{ .Values.global.env | quote }}
  INROAD_REDIS_ADDR: {{ .Values.redis.addr | quote }}
  INROAD_PUBLIC_URL: {{ .Values.global.publicUrl | quote }}
  INROAD_WEB_DIR: "/srv/web"
