apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inroad.fullname" . }}-secret
  labels:
    {{- include "inroad.labels" . | nindent 4 }}
type: Opaque
stringData:
  INROAD_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  INROAD_MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  INROAD_DATABASE_URL: {{ .Values.database.url | quote }}
