-- Make a cross-tenant snooze or label assignment UNREPRESENTABLE rather than
-- merely rejected in Go.
--
-- Migrations 64 and 65 gave inbox_thread_snoozes and inbox_thread_labels a
-- workspace_id alongside their thread_id/label_id, but nothing at the schema
-- level forbade a row whose workspace_id disagreed with its thread's or label's
-- actual workspace. No such row can be written today — every Service writer
-- checks the thread (and the label) in the caller's workspace first, and every
-- read is workspace-pinned, so a mismatched row would be invisible anyway — but
-- that made correctness rest on discipline at three call sites.
--
-- This is the pattern campaign_senders already uses (migration 28): a composite
-- FK, so the database itself refuses the mismatch. The pending-reply table
-- (migration 66) got it right a different way, by taking workspace_id from the
-- thread row via INSERT … SELECT; either shape is sound, and these two tables
-- are cheaper to fix with the constraint than to rewrite.

-- A composite FK needs a unique index on exactly the referenced columns. Both
-- are redundant with the tables' own primary keys for uniqueness purposes, and
-- exist solely to be referenceable.
CREATE UNIQUE INDEX uq_inbox_threads_id_workspace ON inbox_threads (id, workspace_id);
CREATE UNIQUE INDEX uq_inbox_labels_id_workspace ON inbox_labels (id, workspace_id);

-- Replace the single-column references with composite ones. The old constraints
-- are dropped by name; both were generated by Postgres from the column name, so
-- IF EXISTS guards against a hand-migrated database where they differ.
ALTER TABLE inbox_thread_snoozes
    DROP CONSTRAINT IF EXISTS inbox_thread_snoozes_thread_id_fkey,
    ADD CONSTRAINT inbox_thread_snoozes_thread_workspace_fkey
        FOREIGN KEY (thread_id, workspace_id)
        REFERENCES inbox_threads (id, workspace_id) ON DELETE CASCADE;

ALTER TABLE inbox_thread_labels
    DROP CONSTRAINT IF EXISTS inbox_thread_labels_thread_id_fkey,
    ADD CONSTRAINT inbox_thread_labels_thread_workspace_fkey
        FOREIGN KEY (thread_id, workspace_id)
        REFERENCES inbox_threads (id, workspace_id) ON DELETE CASCADE;

ALTER TABLE inbox_thread_labels
    DROP CONSTRAINT IF EXISTS inbox_thread_labels_label_id_fkey,
    ADD CONSTRAINT inbox_thread_labels_label_workspace_fkey
        FOREIGN KEY (label_id, workspace_id)
        REFERENCES inbox_labels (id, workspace_id) ON DELETE CASCADE;

-- The same treatment for the deferred-send tables. inbox_pending_replies is
-- already safe by construction (its INSERT … SELECT derives workspace_id from
-- the thread), but a constraint costs nothing and closes the door on a future
-- writer that forgets.
ALTER TABLE inbox_pending_replies
    DROP CONSTRAINT IF EXISTS inbox_pending_replies_thread_id_fkey,
    ADD CONSTRAINT inbox_pending_replies_thread_workspace_fkey
        FOREIGN KEY (thread_id, workspace_id)
        REFERENCES inbox_threads (id, workspace_id) ON DELETE CASCADE;

CREATE UNIQUE INDEX uq_mailboxes_id_workspace ON mailboxes (id, workspace_id);

ALTER TABLE inbox_pending_composes
    DROP CONSTRAINT IF EXISTS inbox_pending_composes_mailbox_id_fkey,
    ADD CONSTRAINT inbox_pending_composes_mailbox_workspace_fkey
        FOREIGN KEY (mailbox_id, workspace_id)
        REFERENCES mailboxes (id, workspace_id) ON DELETE CASCADE;

-- inbox_compose_drafts is deliberately LEFT ALONE.
--
-- Its mailbox_id is nullable with ON DELETE SET NULL, and a composite FK cannot
-- keep that behaviour: SET NULL nulls every referencing column, which would try
-- to null workspace_id (NOT NULL) and fail the delete outright. The alternatives
-- are worse than the gap — ON DELETE CASCADE would silently destroy an
-- operator's unsent draft because a mailbox was disconnected, and dropping the
-- FK entirely loses the cascade we do want.
--
-- The residual exposure is nil in practice: a draft's mailbox_id is only ever
-- read back to prefill the composer's From picker, and the SEND path
-- (CreateInboxPendingCompose) re-resolves the mailbox through its own
-- workspace-pinned INSERT … SELECT. So a mismatched draft could at worst
-- prefill a picker with a mailbox the operator cannot actually send from, and
-- the send would then be refused.
