DROP TRIGGER IF EXISTS workspaces_seed_default_pipeline ON workspaces;
DROP FUNCTION IF EXISTS seed_new_workspace_pipeline();
DROP FUNCTION IF EXISTS seed_workspace_default_pipeline(UUID);
DROP FUNCTION IF EXISTS seed_pipeline_stages(UUID, UUID);
DROP TABLE IF EXISTS task_targets;
DROP TABLE IF EXISTS note_targets;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS deals;
DROP TABLE IF EXISTS pipeline_stages;
DROP TABLE IF EXISTS pipelines;
DROP TRIGGER IF EXISTS contacts_touch_updated_at ON contacts;
DROP TRIGGER IF EXISTS contacts_sync_primary_email ON contacts;
DROP FUNCTION IF EXISTS sync_contact_primary_email();
DROP TABLE IF EXISTS contact_emails;
ALTER TABLE contacts DROP CONSTRAINT IF EXISTS contacts_company_tenant_fkey;
ALTER TABLE contacts DROP COLUMN IF EXISTS updated_at;
ALTER TABLE contacts DROP COLUMN IF EXISTS linkedin_url;
ALTER TABLE contacts DROP COLUMN IF EXISTS job_title;
ALTER TABLE contacts DROP COLUMN IF EXISTS company_id;
DROP TABLE IF EXISTS companies;
DROP FUNCTION IF EXISTS crm_touch_updated_at();
