#!/bin/sh
# Inroad self-host installer.
#
# Pulls published container images and brings up Postgres, Redis, the API,
# and the worker — no git clone, no Go or Node toolchain. Usage:
#
#   curl -fsSL https://raw.githubusercontent.com/Axomble/Inroad/main/scripts/install.sh | sh
#
# or, to preview without touching anything:
#
#   curl -fsSL .../install.sh | sh -s -- --dry-run
#
# Hard rules this script follows, and why:
#
#   - POSIX sh, not bash. Alpine and BusyBox images (which is what most of
#     this fleet runs on) have no bash; `local`, `[[ ]]`, arrays, and
#     `function name()` are all bash-only and are deliberately never used
#     here even though this happens to run under bash sometimes too.
#   - `set -eu`: an unset variable or a failed command aborts immediately.
#   - `main "$@"` is the LAST line of this file. A `curl | sh` pipe that gets
#     cut off mid-download (a flaky connection, a killed process) leaves a
#     truncated script on the interpreter's stdin — if `main` were invoked
#     any earlier, a truncation could still execute a partial command with
#     whatever bytes happened to arrive. Putting the call last means a
#     truncated download simply never reaches it: the shell hits EOF while
#     still parsing, and nothing runs.
#   - Idempotent. Re-running never touches an existing .env or its secrets:
#     INROAD_MASTER_KEY seals every stored credential (mailbox passwords,
#     OAuth tokens) via envelope encryption, and regenerating it over an
#     existing value makes every one of them permanently undecryptable —
#     there is no way back from that, so a secret is generated only when the
#     file is genuinely absent, and the script says so either way.
set -eu

# ---- configuration (all overridable via environment) -----------------------
INROAD_REPO_RAW_BASE=${INROAD_REPO_RAW_BASE:-https://raw.githubusercontent.com/Axomble/Inroad/main}
INROAD_INSTALL_DIR=${INROAD_INSTALL_DIR:-./inroad}
INROAD_IMAGE_REPO=${INROAD_IMAGE_REPO:-ghcr.io/axomble/inroad}
INROAD_VERSION=${INROAD_VERSION:-latest}
API_PORT=${API_PORT:-8080}

DRY_RUN=0

usage() {
    cat <<'EOF'
Inroad self-host installer.

Usage: install.sh [--dry-run] [--dir DIR] [-h|--help]

  --dry-run     Print every step without touching anything: no files
                written, no secrets generated, no docker command run.
  --dir DIR     Install into DIR instead of ./inroad.
  -h, --help    Show this help and exit.

Environment overrides:
  INROAD_REPO_RAW_BASE  where the compose manifest is fetched from
                         (default: the main branch on GitHub)
  INROAD_IMAGE_REPO     image repository prefix
                         (default: ghcr.io/axomble/inroad)
  INROAD_VERSION        image tag to pull (default: latest)
  API_PORT              host port the app is published on (default: 8080)
EOF
}

log() { printf '%s\n' "$*"; }
err() { printf 'install.sh: %s\n' "$*" >&2; }

# run is the ONE place every side-effecting step in this script goes
# through: it always prints the command first, then executes it unless
# --dry-run was given. A step added anywhere else would bypass --dry-run's
# guarantee, so nothing in main() below calls docker/curl/mkdir directly.
run() {
    log "+ $*"
    if [ "$DRY_RUN" -eq 0 ]; then
        "$@"
    fi
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "$1 is required but was not found on PATH"
        exit 1
    fi
}

# gen_secret prints n random bytes, base64-encoded on one line. Used for both
# INROAD_MASTER_KEY (must decode to EXACTLY 32 bytes — internal/platform/
# config.go rejects anything else, since it is unpacked straight into
# AES-256) and INROAD_JWT_SECRET / POSTGRES_PASSWORD (no exact-length
# requirement beyond config.go's >= 16-byte floor for the JWT secret; a
# generous length is used for both anyway).
gen_secret() {
    n=$1
    openssl rand -base64 "$n" | tr -d '\n'
}

# write_env creates path with freshly generated secrets, UNLESS it already
# exists — see the idempotency rule in the file header. In --dry-run mode it
# never touches the filesystem or /dev/urandom, even to check what it would
# generate, since a preview must have zero side effects.
write_env() {
    path=$1
    if [ -f "$path" ]; then
        log "$path already exists — leaving it and its secrets untouched."
        return 0
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
        log "+ (dry run) would generate $path with a fresh POSTGRES_PASSWORD, INROAD_JWT_SECRET, and INROAD_MASTER_KEY"
        return 0
    fi
    log "Generating $path with fresh secrets (this happens exactly once — re-running install.sh will not touch them again)..."
    jwt_secret=$(gen_secret 48)
    master_key=$(gen_secret 32)
    pg_password=$(gen_secret 24)
    umask 077
    {
        printf '# Generated by install.sh on %s.\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '# Keep this file secret and back it up: INROAD_MASTER_KEY seals every\n'
        printf '# stored credential. Losing it loses them all; regenerating it over this\n'
        printf '# value makes every one of them permanently undecryptable.\n'
        printf 'POSTGRES_PASSWORD=%s\n' "$pg_password"
        printf 'INROAD_JWT_SECRET=%s\n' "$jwt_secret"
        printf 'INROAD_MASTER_KEY=%s\n' "$master_key"
        printf 'INROAD_PUBLIC_URL=http://localhost:%s\n' "$API_PORT"
        printf 'API_PORT=%s\n' "$API_PORT"
    } > "$path"
    chmod 600 "$path"
}

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --dry-run)
                DRY_RUN=1
                shift
                ;;
            --dir)
                [ $# -ge 2 ] || { err "--dir requires a value"; exit 2; }
                INROAD_INSTALL_DIR=$2
                shift 2
                ;;
            --dir=*)
                INROAD_INSTALL_DIR=${1#--dir=}
                shift
                ;;
            -h | --help)
                usage
                exit 0
                ;;
            *)
                err "unknown argument: $1"
                usage >&2
                exit 2
                ;;
        esac
    done
}

main() {
    parse_args "$@"
    # Exported once so `docker compose`'s own variable interpolation (the
    # ${INROAD_IMAGE_REPO:-...} references in the compose manifest) sees
    # them, without re-stating an `env VAR=... VAR2=...` prefix on every
    # invocation below.
    export INROAD_IMAGE_REPO INROAD_VERSION

    require_cmd docker
    require_cmd curl
    require_cmd openssl
    if ! docker compose version >/dev/null 2>&1; then
        err "docker compose (the v2 plugin) is required — https://docs.docker.com/compose/install/"
        exit 1
    fi

    log "Installing Inroad into $INROAD_INSTALL_DIR"
    run mkdir -p "$INROAD_INSTALL_DIR"

    compose_file="$INROAD_INSTALL_DIR/docker-compose.yml"
    manifest_url="$INROAD_REPO_RAW_BASE/deploy/docker/docker-compose.prod.yml"
    log "Fetching the compose manifest (pulls published images — nothing is built locally)..."
    run curl -fsSL -o "$compose_file" "$manifest_url"

    env_file="$INROAD_INSTALL_DIR/.env"
    write_env "$env_file"

    log "Pulling images ($INROAD_IMAGE_REPO, tag $INROAD_VERSION)..."
    run docker compose --project-directory "$INROAD_INSTALL_DIR" -f "$compose_file" --env-file "$env_file" pull

    log "Starting Postgres, Redis, the API, and the worker..."
    run docker compose --project-directory "$INROAD_INSTALL_DIR" -f "$compose_file" --env-file "$env_file" up -d

    log ""
    if [ "$DRY_RUN" -eq 1 ]; then
        log "Dry run: nothing was written, generated, or started."
        return 0
    fi
    log "Inroad is starting at http://localhost:$API_PORT"
    log ""
    log "Create your first account (inroadctl is baked into the api image, so"
    log "this needs nothing beyond docker):"
    log ""
    log "  cd $INROAD_INSTALL_DIR && docker compose exec api inroadctl create-user --email you@example.com"
    log ""
    log "It reads the password from the prompt it opens — never pass one as a flag."
    log "See \`docker compose exec api inroadctl help\` for the rest (set-password,"
    log "grant-role, workspaces, users, status)."
}

main "$@"
